import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// This viewer is deliberately framework-free. It is copied into every run
// artifact so the runner can evolve independently from the general Midscene
// report application and from @midscene/core's report dump format.
const viewerHtml = String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Midscene Test Report</title>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #172033; background: #f5f7fb; }
    * { box-sizing: border-box; }
    body { margin: 0; min-width: 900px; }
    button { font: inherit; }
    .topbar { min-height: 70px; padding: 16px 28px; display: flex; align-items: center; justify-content: space-between; color: #fff; background: linear-gradient(115deg, #14213d, #263f72); }
    .brand { font-size: 18px; font-weight: 720; letter-spacing: -.02em; }
    .run { margin-top: 4px; color: #b9c9ec; font: 12px ui-monospace, SFMono-Regular, Menlo, monospace; }
    .status { padding: 7px 11px; border-radius: 999px; font-size: 12px; font-weight: 700; background: #e8f7ed; color: #146b35; }
    .status.failed { background: #fdeaea; color: #a51d2d; }
    .layout { display: grid; grid-template-columns: 365px minmax(0, 1fr); min-height: calc(100vh - 70px); }
    .sidebar { overflow: auto; padding: 20px; border-right: 1px solid #e1e6ef; background: #fff; }
    .summary { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 19px; }
    .metric { padding: 12px; border-radius: 10px; background: #f5f7fb; }
    .metric b { display: block; margin-bottom: 3px; font-size: 20px; }
    .metric span { color: #677188; font-size: 12px; }
    .filter { width: 100%; margin-bottom: 14px; padding: 9px 11px; border: 1px solid #d8dfeb; border-radius: 8px; outline-color: #395eac; }
    .source { margin: 17px 0 7px; color: #68738a; font-size: 12px; font-weight: 700; }
    .case { width: 100%; display: grid; grid-template-columns: 18px minmax(0, 1fr); gap: 9px; padding: 11px 9px; border: 0; border-radius: 8px; text-align: left; cursor: pointer; color: inherit; background: transparent; }
    .case:hover { background: #f3f6fb; }.case.selected { background: #e9f0ff; }.case-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 13px; font-weight: 620; }.case-meta { margin-top: 4px; color: #778298; font-size: 11px; }.dot { width: 9px; height: 9px; margin-top: 4px; border-radius: 50%; background: #28a05d; }.dot.failed { background: #db3c4c; }.dot.blocked { background: #a18b59; }.main { overflow: auto; padding: 30px 38px 55px; }.empty { padding: 50px; text-align: center; color: #69748b; }.case-head { padding-bottom: 21px; border-bottom: 1px solid #dfe5ee; }.eyebrow { color: #64718b; font-size: 12px; }.title-row { display: flex; gap: 13px; align-items: baseline; }.title-row h1 { margin: 7px 0 5px; font-size: 27px; letter-spacing: -.035em; }.details { color: #67738a; font-size: 13px; }.failure { margin: 18px 0 0; padding: 14px 16px; border-left: 4px solid #d6364c; border-radius: 7px; color: #7e1f2d; background: #fff0f1; }.section { margin-top: 28px; }.section h2 { margin: 0 0 11px; font-size: 14px; }.step { width: 100%; margin: 7px 0; padding: 13px 15px; border: 1px solid #dde4ee; border-radius: 9px; text-align: left; background: #fff; cursor: pointer; }.step:hover { border-color: #9eb5e5; }.step.failed { border-color: #e77281; background: #fff7f7; }.step-top { display: flex; gap: 10px; align-items: center; }.step-status { font-size: 12px; font-weight: 800; color: #198348; }.step-status.failed { color: #c22c40; }.step-name { font-weight: 700; }.step-time { margin-left: auto; color: #718099; font-size: 12px; }.step-summary { margin: 7px 0 0 28px; color: #4f5b70; font-size: 13px; line-height: 1.5; }.step-detail { display: none; margin: 12px 0 0 28px; }.step.open .step-detail { display: block; }.step pre { overflow: auto; margin: 8px 0; padding: 10px; border-radius: 6px; color: #d9e6ff; background: #17223b; font: 12px/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }.actions { display: flex; gap: 8px; align-items: center; margin-top: 11px; }.copy, .report-link { padding: 6px 9px; border: 1px solid #ccd7eb; border-radius: 6px; color: #294a89; background: #fff; cursor: pointer; font-size: 12px; text-decoration: none; }.hook { margin: 7px 0; padding: 11px 14px; border-radius: 8px; border: 1px dashed #c8d2e1; color: #4f5c73; background: #fafbfd; }.hook summary { cursor: pointer; font-weight: 700; }.error { margin: 30px; padding: 16px; color: #951f31; border-radius: 8px; background: #ffeff1; }
  </style>
</head>
<body><header class="topbar"><div><div class="brand">Midscene Test Report</div><div id="run" class="run">Loading run…</div></div><div id="status" class="status">Loading</div></header><div class="layout"><aside class="sidebar"><div id="summary" class="summary"></div><input id="filter" class="filter" placeholder="Filter cases" /><div id="case-list"></div></aside><main id="main" class="main"><div class="empty">Loading test results…</div></main></div>
<script>
const state = { summary: null, cases: [], selected: null };
const duration = (ms) => ms < 1000 ? ms + ' ms' : (ms / 1000).toFixed(ms >= 10000 ? 0 : 1) + ' s';
const text = (value) => value == null ? '' : String(value);
const element = (tag, className, value) => { const el = document.createElement(tag); if (className) el.className = className; if (value !== undefined) el.textContent = value; return el; };
const failureOf = (attempt) => [...(attempt.beforeEach || []), ...(attempt.steps || []), ...(attempt.afterEach || [])].find((step) => step.status === 'failed');
const failureText = (item) => { const final = item.attempts && item.attempts[item.attempts.length - 1]; const step = final && final.data ? failureOf(final.data) : null; return step && step.error ? text(step.error.message) : step ? text(step.output && step.output.summary) : item.notRunReason === 'document-start-failed' ? 'Blocked by beforeAll failure' : ''; };
const setHash = (item) => history.replaceState(null, '', '#case=' + encodeURIComponent(item.caseId));
async function json(path) { const response = await fetch('../' + path); if (!response.ok) throw new Error('Could not load ' + path); return response.json(); }
async function loadCase(item) { if (item.loaded) return; item.attempts = await Promise.all((item.attempts || []).map(async (attempt) => ({ ...attempt, data: await json(attempt.resultFile) }))); item.loaded = true; }
function renderSummary() { const s = state.summary.summary; const values = [[s.total, 'Cases'], [s.failed, 'Failed'], [s.passed, 'Passed'], [s.notRun, 'Blocked']]; const root = document.getElementById('summary'); root.replaceChildren(...values.map(([value, label]) => { const box = element('div', 'metric'); box.append(element('b', '', value), element('span', '', label)); return box; })); }
function renderList() { const root = document.getElementById('case-list'); const query = document.getElementById('filter').value.trim().toLowerCase(); root.replaceChildren(); const groups = new Map(); for (const item of state.cases) { if (query && !item.name.toLowerCase().includes(query) && !item.sourcePath.toLowerCase().includes(query)) continue; const group = groups.get(item.sourcePath) || []; group.push(item); groups.set(item.sourcePath, group); } for (const [source, items] of groups) { root.append(element('div', 'source', source)); for (const item of items) { const button = element('button', 'case' + (state.selected === item ? ' selected' : '')); const dot = element('span', 'dot' + (item.status === 'failed' ? ' failed' : item.status === 'not-run' ? ' blocked' : '')); const content = element('span'); content.append(element('span', 'case-name', item.name), element('span', 'case-meta', item.status === 'not-run' ? 'Blocked' : item.status === 'failed' ? failureText(item) || 'Failed' : 'Passed')); button.append(dot, content); button.onclick = () => select(item, true); root.append(button); } } }
function stepCard(step) { const failed = step.status === 'failed'; const card = element('button', 'step' + (failed ? ' failed' : '')); const top = element('div', 'step-top'); top.append(element('span', 'step-status' + (failed ? ' failed' : ''), failed ? 'FAILED' : 'PASSED'), element('span', 'step-name', step.node), element('span', 'step-time', duration(step.durationMs))); card.append(top); const summary = text(step.error && step.error.message) || text(step.output && step.output.summary); if (summary) card.append(element('div', 'step-summary', summary)); const detail = element('div', 'step-detail'); detail.append(element('strong', '', 'Input')); const input = element('pre'); input.textContent = JSON.stringify(step.input, null, 2); detail.append(input); if (step.error || step.output) { detail.append(element('strong', '', step.error ? 'Error' : 'Output')); const output = element('pre'); output.textContent = JSON.stringify(step.error || step.output, null, 2); detail.append(output); } const actions = element('div', 'actions'); const copy = element('button', 'copy', 'Copy diagnostic'); copy.type = 'button'; copy.onclick = (event) => { event.stopPropagation(); navigator.clipboard.writeText(JSON.stringify({ node: step.node, phase: step.phase, input: step.input, error: step.error, output: step.output }, null, 2)); copy.textContent = 'Copied'; setTimeout(() => copy.textContent = 'Copy diagnostic', 1200); }; actions.append(copy); detail.append(actions); card.append(detail); card.onclick = () => card.classList.toggle('open'); return card; }
function stepsSection(title, steps, hooks) { if (!steps || !steps.length) return null; const section = element('section', 'section'); section.append(element('h2', '', title)); if (hooks) { const wrapper = element('details', 'hook'); wrapper.append(element('summary', '', title + ' · ' + steps.length + ' steps')); steps.forEach((step) => wrapper.append(stepCard(step))); section.replaceChildren(wrapper); } else steps.forEach((step) => section.append(stepCard(step))); return section; }
async function renderDetail(item) { const main = document.getElementById('main'); main.replaceChildren(element('div', 'empty', 'Loading case details…')); await loadCase(item); const attempt = item.attempts[item.attempts.length - 1]; const data = attempt && attempt.data; const head = element('div', 'case-head'); head.append(element('div', 'eyebrow', item.sourcePath + ' · attempt ' + ((attempt && attempt.attemptIndex) + 1)), element('div', 'title-row')); head.querySelector('.title-row').append(element('h1', '', item.name)); head.append(element('div', 'details', (data ? duration(data.durationMs) : 'Not executed') + ' · ' + (item.status === 'not-run' ? 'Blocked' : item.status))); const failed = data && failureOf(data); if (failed) head.append(element('div', 'failure', 'Failed at ' + failed.phase + ' step ' + (failed.stepIndex + 1) + ': ' + (text(failed.error && failed.error.message) || text(failed.output && failed.output.summary)))); const fragment = document.createDocumentFragment(); fragment.append(head); const project = state.summary.projects.find((p) => p.projectId === item.projectId); const workflowDocument = project && project.documents.find((d) => d.documentId === item.documentId); if (workflowDocument && !workflowDocument.data) workflowDocument.data = await json(workflowDocument.resultFile); if (workflowDocument && workflowDocument.data) { const before = stepsSection('beforeAll', workflowDocument.data.beforeAll, true); if (before) fragment.append(before); } if (data) { const beforeEach = stepsSection('beforeEach', data.beforeEach, true); if (beforeEach) fragment.append(beforeEach); const steps = stepsSection('Steps', data.steps, false); if (steps) fragment.append(steps); const afterEach = stepsSection('afterEach', data.afterEach, true); if (afterEach) fragment.append(afterEach); } if (workflowDocument && workflowDocument.data) { const after = stepsSection('afterAll', workflowDocument.data.afterAll, true); if (after) fragment.append(after); } const reports = (attempt && attempt.reports) || []; if (reports.length) { const section = element('section', 'section'); section.append(element('h2', '', 'Raw execution reports')); reports.forEach((path, i) => { const link = element('a', 'report-link', 'Open report ' + (i + 1)); link.href = '../' + path; link.target = '_blank'; section.append(link); }); fragment.append(section); } main.replaceChildren(fragment); }
async function select(item, updateHash) { state.selected = item; if (updateHash) setHash(item); renderList(); try { await renderDetail(item); } catch (error) { document.getElementById('main').replaceChildren(element('div', 'error', text(error.message || error))); } }
async function start() { try { state.summary = await (await fetch('../summary.json')).json(); document.getElementById('run').textContent = state.summary.runId + ' · ' + new Date(state.summary.startedAt).toLocaleString(); const status = document.getElementById('status'); status.textContent = state.summary.status.toUpperCase(); if (state.summary.status === 'failed') status.classList.add('failed'); state.cases = state.summary.projects.flatMap((project) => project.cases.map((item) => ({ ...item, projectId: project.projectId }))).sort((a, b) => (a.status === 'failed' ? -1 : 0) - (b.status === 'failed' ? -1 : 0) || a.sourcePath.localeCompare(b.sourcePath) || a.caseIndex - b.caseIndex); renderSummary(); document.getElementById('filter').oninput = renderList; const wanted = new URLSearchParams(location.hash.slice(1)).get('case'); const selected = state.cases.find((item) => item.caseId === wanted) || state.cases.find((item) => item.status === 'failed') || state.cases[0]; renderList(); if (selected) select(selected, !wanted); else document.getElementById('main').replaceChildren(element('div', 'empty', 'This run contains no cases.')); } catch (error) { document.getElementById('main').replaceChildren(element('div', 'error', text(error.message || error))); } }
start();
</script></body></html>`;

export const testReportViewerPath = (runDir: string): string =>
  join(runDir, 'report', 'index.html');

export const writeTestReportViewer = (runDir: string): string => {
  const path = testReportViewerPath(runDir);
  mkdirSync(join(runDir, 'report'), { recursive: true });
  writeFileSync(path, viewerHtml, 'utf8');
  return path;
};
